### PR TITLE
 Bump to Borg 1.2.2

### PR DESCRIPTION
**Pull request by amteza**
Update Borgbackup to version 1.2.2, no other changes required for the formula to work.

### CODE REVIEW

**Review by ThomasWaldmann — APPROVED** [review]
LGTM.

**Comment by ThomasWaldmann** [comment]
@amteza thanks for the PR, but it looks like some (new?) linter is unhappy about a missing space, can you fix it?

**Comment by amteza** [comment]
> @amteza thanks for the PR, but it looks like some (new?) linter is unhappy about a missing space, can you fix it?

Should be fixed now. I saw it during the "brew audit" and forgot to add the space, apologies.

**Comment by ThomasWaldmann** [comment]
Thanks!

**Pull request merged**
