### PR TITLE
update borg version to 1.1.17

### PR DESCRIPTION
**Pull request by knutov**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@knutov did you try the formula? there is a new "packaging" depdendency since 1.1.17.

if not, can you try right after I merge?

**Comment by ThomasWaldmann** [comment]
Our tests have discovered the issue I suspected, so the formula needs updates somehow:
```
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by m3nu** [comment]
Shouldn't be a big change. I can take care of it in a few days. Or @knutov, if he gets there before me.

**Comment by knutov** [comment]
Well, I tried, but should admit I do not understand how brew works and even how to run formulae from local script :(

brew documentation clearly says:

> An arbitrary file: Homebrew can install formulae from a local path. It can point to either a formula file or a bottle. Prefix relative paths with ./ to prevent them from being interpreted as a formula or tap name

but with `brew install ./borgbackup-fuse.rb` it still wants to full tap name to download from internet

@m3nu please fix this PR if you can.

**Comment by knutov** [comment]
`brew untap borgbackup/tap` helped to install from local file.

`pip3 install packaging` should be added to install script, but I do not understand what code should I write for this.

Everything works if I do it manually before `brew install ./homebrew-tap/Formula/borgbackup-fuse.rb`

**Comment by m3nu** [comment]
No worries. I'll wrap it up. Just needs the new dependency added.

**Comment by m3nu** [comment]
Added the new `packaging` dependency and checks out now. Anything else you can think of, @knutov ?

**Comment by ThomasWaldmann** [comment]
@m3nu thanks for fixing the formula.

In the CI logs, there are some strange warnings. Can they be fixed or just ignore them?

**Comment by m3nu** [comment]
You mean the one below? I always get that when running a formula from a file. Should be fine.

```
Error: Failed to load cask: borgbackup-fuse.rb
Cask 'borgbackup-fuse' is unreadable: wrong constant name #<Class:0x00007f8eaba7aaf8>
Warning: Treating borgbackup-fuse.rb as a formula.
```

**Comment by ThomasWaldmann** [comment]
Yeah, that one. OK, so we ignore it.

**Pull request merged**
